"""Add nullable field

Revision ID: 1ea93f741cf2
Revises: 201e4eaeb9d4
Create Date: 2020-11-09 09:44:32.037699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea93f741cf2'
down_revision = '201e4eaeb9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'brief',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.create_unique_constraint(None, 'posts', ['slug'])
    op.create_unique_constraint(None, 'tags', ['slug'])
    op.create_unique_constraint(None, 'tags', ['name'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('posts', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'brief',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
