"""update vote

Revision ID: 4bd105e8b688
Revises: 1ea93f741cf2
Create Date: 2020-12-09 08:31:20.716860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd105e8b688'
down_revision = '1ea93f741cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_vote_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'vote_id')
    op.add_column('votes', sa.Column('post_id', sa.Integer(), nullable=False))
    op.add_column('votes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('votes', sa.Column('vote', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'votes', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'])
    op.drop_column('votes', 'upvote')
    op.drop_column('votes', 'downvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'vote')
    op.drop_column('votes', 'user_id')
    op.drop_column('votes', 'post_id')
    op.add_column('posts', sa.Column('vote_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_vote_id_fkey', 'posts', 'votes', ['vote_id'], ['id'])
    # ### end Alembic commands ###
