"""update thumbnail to post

Revision ID: 922ff09d6bed
Revises: 1ea93f741cf2
Create Date: 2020-12-11 10:35:50.574720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922ff09d6bed'
down_revision = '1ea93f741cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumbnail')
    # ### end Alembic commands ###
