version: "3.5"

services:
  web:
    image: techblog:latest
    env_file:
      - .env
    command: gunicorn -w 4 -b 0.0.0.0:5000 src.main:app
    restart: unless-stopped
    ports:
      - "8080:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "5"
